server.port=8080
spring.application.name=pomguard

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# INSTANT UI UPDATES: Direct file loading
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=file:d:/PROJECTS/Pomguard/src/main/resources/templates/
spring.web.resources.static-locations=file:d:/PROJECTS/Pomguard/src/main/resources/static/
